### ISSUE TITLE
This demo does not work with Beaglebone

### ISSUE THREAD

**Issue by FRVisser** [resin-io-projects/resin-watchdog#1]
The dockerfile.template suggest this is a cross platform demo. But this application is only made for `bcm2708` chipsets.

**Comment by craigmulligan** [comment]
Thanks @FRVisser I've updated the readme. https://github.com/resin-io-projects/resin-watchdog/commit/cff03243d2c544c8c464a239d7b35861d4f6d6ad I'll close now. Feel free to open if this doesn't suffice.
